# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheBattleOfLV7000' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

  # Pods for TheBattleOfLV7000

   pod 'Firebase/Analytics'
   pod 'Firebase/Database'
   pod 'Firebase/Auth'
   pod 'Firebase/Firestore'


end
